steps:
- id: 'buildImage'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.35.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    skaffold build --file-output /workspace/image.json
- id: 'validate signature'
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    SRC_IMAGE="$(cat /workspace/image.json | jq -r '.builds[0].tag' | sed 's/\:latest//g')"
    wget https://github.com/slsa-framework/slsa-verifier/releases/download/v1.4.1-rc/slsa-verifier-linux-amd64
    mv slsa-verifier-linux-amd64 slsa-verifier

    gcloud artifacts docker images describe "${SRC_IMAGE}" --format json --show-provenance > /workspace/provenance.json
    cat /workspace/provenance.json
    ./slsa-verifier verify-image "${SRC_IMAGE}" \
      --provenance-path provenance.json \
      --source-uri https://github.com/shawnho1018/hello-k8s-summit \
      --builder-id=https://cloudbuild.googleapis.com/GoogleHostedWorker
    
    gcloud artifacts docker images scan ${SRC_IMAGE}:latest \
      --format='value(response.scan)' --remote > /workspace/scan_id.txt

- id: 'Check cve'
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Check Image CVE"
    gcloud artifacts docker images list-vulnerabilities $(cat /workspace/scan_id.txt) \
    --format='value(vulnerability.effectiveSeverity, vulnerability.shortDescription)' > result.txt
    cat result.txt
    if (cat result.txt | grep -Fxq $_SEVERITY | grep -vFxq $_NEGLECT_CVE); then
      echo 'Failed vulnerability check' && exit 1
    else
      echo 'Passed the CVE vulnerability check'
    fi
- id: 'provide SBOM'
  name: 'spdx/spdx-sbom-generator'
  entrypoint: sh
  args:
  - '-c'
  - |
    /spdx-sbom-generator -p . -o /workspace/
- id: 'trigger skaffold deploy'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.35.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    skaffold deploy -p cloudbuild --build-artifacts=/workspace/image.json
substitutions:
  _SEVERITY: CRITICAL
  _NEGLECT_CVE: CVE-2022-1292
timeout: 1200s