steps:
- id: 'DSAT Test with Zap'
  name: owasp/zap2docker-stable
  entrypoint: 'bash'
  args: 
  - '-c'
  - |
    export HOME=`pwd`
    touch zap.yaml
    zap-baseline.py -t http://35.189.173.44

substitutions:
  _SEVERITY: CRITICAL
  _NEGLECT_CVE: CVE-2022-1292
  _CLUSTER_NAME: k8s-summit
  _CLUSTER_LOCATION: asia-east1-a
  _IMAGE_PATH: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-k8s-summit
  _PROJECT_ID: shawn-demo-2022