steps:
- id: 'buildImage'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    build -t ${_IMAGE_PATH}:latest
- id: 'trigger skaffold deploy'
  name: 'gcr.io/k8s-skaffold/skaffold:v1.35.1'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials ${_CLUSTER_NAME} --zone ${_CLUSTER_LOCATION} --project ${_PROJECT_ID}
    ImageDigest="$(gcloud container images list-tags --format='get(digest)' ${_IMAGE_PATH} | head -1)"
    skaffold deploy -p cloudbuild --tag $ImageDigest
substitutions:
  _CLUSTER_NAME: k8s-summit
  _CLUSTER_LOCATION: asia-east1-a
  _IMAGE_PATH: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-k8s-summit
  _PROJECT_ID: shawn-demo-2022