apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: cloudbuild-attestor
spec:
  images:
  - glob: "**"
  authorities:
  - name: custom-key
    key:
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEeDm/Gx1BcscmeEwHlX0J/u/tiCDP
        YIepJFr71xZ0TGJgW/ESzp3wf97L0E9mnKLp5tpFJIhTEa+3fyaLrSm1Dw==
        -----END PUBLIC KEY-----
    attestations:
    - name: must-have-cosign-sigstore-sign
      predicateType: custom
      policy:
        data: |
          import "time"
          predicateType: "cosign.sigstore.dev/attestation/v1"
        type: cue

