apiVersion: cosigned.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: cloudbuild-attestor
spec:
  authorities:
  - attestations:
    - name: customkey
      policy:
        data: |
          import "time"
          before: time.Parse(time.RFC3339, "2021-10-09T17:10:27Z")
          predicateType: "cosign.sigstore.dev/attestation/v1"

          // The predicate must match the following constraints.
          predicate: {
            Data: "Image-Scan\n"
            Timestamp: >before
          }
        type: cue
      predicateType: custom
    key:
      data: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBClcqTrntaXxmpwzPbPCfAEtPRW+
        fmhP5lEIW3GPQW5q44ovycz+8oXKw5Yf3hfKANAGbPjW9gIY7d8osj1mSQ==
        -----END PUBLIC KEY-----
    name: authority-0
  images:
  - regex: .*