apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: cloudbuild-attestor
spec:
  images:
  - glob: "**"
  authorities:
  - name: custom-key
    key:
      secretRef:
        name: mysecret
    attestations:
    - name: must-have-cosign-sigstore-sign
      predicateType: custom
      policy:
        data: |
          import "time"
          predicateType: "cosign.sigstore.dev/attestation/v1"
        type: cue

